# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbd182684ae96fb8a2e7d9b6c0680427c8a15769c3049689706631d874aefefd216f756163074421eafd14605690628c944e9112d062bd48284bb1a3be7ba214

test:
  secret_key_base: 01ef971c3ddbeadc7b9f5872eb4da6f1b48588fcd893307ec129edad3f1e0813b4651ae0907f521ba400aeab2f6a5d003664a3e0be56460dde5a6e930131fe4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
